<a href="https://colab.research.google.com/github/ogwora/hello-world/blob/master/Python_Programming_Simple_Random_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [1]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [8]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [40, 20, 80]
Choosing 3 random items from a list using sample function [20, 20, 40]


### <font color="green"> 1.0 Challenges</font>

In [16]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties=['Mombasa','Kwale','Kilifi','Tana River','Lamu','Taita/Taveta','Garissa','Wajir','Mandera','Marsabit']
print("Choosing 2 random counties from the list",random.sample(counties, k=2))

Choosing 2 random counties from the list ['Kilifi', 'Mandera']


## 2.0  Selecting the Random Sample from Dictionary

In [17]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Donald', 60), ('jhon', 70)]


### <font color="green">2.0 Challenges</font>

In [20]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#
food_pkg = {
"bronze_package": {"starch":"rice", "stew":"chicken curry", "vegetable":"cabbages", "desert":"melon"},
"silver_package": {"starch":"rice and chappati",  "stew":"beef curry", "vegetable":"spinach", "desert":"melon and bananas"},
"gold_package": {"starch":"rice, chappati and mukimo", "stew":"beef curry", "vegetable":"spinach and managu", "desert": "tart"}
}

print ("Choosing 2 random food packages from a dictionary using sample method ", random.sample(food_pkg.items(), k=2))

Choosing 2 random food packages from a dictionary using sample method  [('gold_package', {'starch': 'rice, chappati and mukimo', 'stew': 'beef curry', 'vegetable': 'spinach and managu', 'desert': 'tart'}), ('silver_package', {'starch': 'rice and chappati', 'stew': 'beef curry', 'vegetable': 'spinach', 'desert': 'melon and bananas'})]


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [21]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Nadal', 'Novac', 'Nadal']


### <font color="green">3.0 Challenges</font>

In [25]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print("random sample with replacement to including repetition ", random.choices(months, k=3))

random sample with replacement to including repetition  ['June', 'February', 'February']


## 4.0 Selecting a Random Sample from a Range of Integers

In [26]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [65, 40, 80, 75]


### <font color="green">4.1 Challenges</font>

In [30]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

print ("Choosing a random item from a set ", random.sample(weight_set, k=1))

Choosing a random item from a set  [5]


## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [33]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 5 10 15]
[ 5 10 15]


### <font color="green">5.0 Challenges</font>

In [39]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = [[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]  
array=np.array(a)
print("Printing 2D Array")
print(a)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(7, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1, 2, 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]]
Selecting multiple random rows from the 2D array
[ 2  4  6  8 10]
[ 2  4  6  8 10]


## 6.0 Selecting Random Samples from a Dataset

In [41]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]
          PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
30579  2.949249e+14        5637612      M  ...       0            0       No
14940  7.566115e+11        5713957      M  ...       0            0       No
93202  3.371399e+13        5734551      M  ...       0            1       No
86186  8.963877e+14        5769884      F  ...       0            0       No
6332   4.751234e+12        5682086      F  ...       0            0       No
87683  7.153622e+13        5715711      F  ...       0          

### <font color="green">6.0 Challenges </font>

In [42]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
russia_df = pd.read_csv("http://bit.ly/DSRussianInvestigation")

# Determining the size
print(russia_df.shape)


# Previewing the dataset
print(russia_df.head())

# Selecting the sample 
russia_sample = russia_df.sample(n = 10, replace="False")
print(russia_sample)

(194, 13)
  investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon
2     watergate          1973-05-19  ...     True  Richard Nixon
3     watergate          1973-05-19  ...     True  Richard Nixon
4     watergate          1973-05-19  ...     True  Richard Nixon

[5 rows x 13 columns]
       investigation investigation-start  ... american      president
183           russia          2017-05-17  ...    False   Donald Trump
87       iran-contra          1986-12-19  ...     True  Ronald Reagan
128       whitewater          1994-08-05  ...     True   Bill Clinton
74   raymond-donovan          1981-12-29  ...     True  Ronald Reagan
2          watergate          1973-05-19  ...     True  Richard Nixon
71         watergate          1973-05-19  ...     True  Richard Nixon
35         watergate          1973-05-19  ...     True  Richard Nixon
166           rus

In [51]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

appointment_df=df[(df['SMS_received'] == 1) & ( df['No-show']=='Yes')]


# Dataset size
print(appointment_df.shape)

# Selecting the sample 
appointment_sample = appointment_df.sample(n = 50, replace="False")
print(appointment_sample)

(9784, 14)
           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
19443   8.264823e+14        5624438      F  ...       0            1      Yes
97039   9.736987e+13        5627971      M  ...       0            1      Yes
89580   7.499400e+13        5674297      F  ...       0            1      Yes
36838   1.389518e+13        5426425      M  ...       0            1      Yes
36228   2.616696e+12        5722220      F  ...       0            1      Yes
9290    8.221459e+14        5671588      M  ...       0            1      Yes
17332   7.559474e+12        5643323      F  ...       0            1      Yes
2178    2.387167e+14        5577532      F  ...       0            1      Yes
46522   1.966467e+13        5624249      F  ...       0            1      Yes
85817   2.334776e+11        5772568      F  ...       0            1      Yes
37722   7.243564e+12        5725646      M  ...       1            1      Yes
60729   9.969569e+12        5585787      F  ...      